### PR TITLE
config: Add dotdoom (doom-emacs) HaoZeke

### PR DESCRIPTION
**Pull request by HaoZeke**
You could check the config out [here too](https://dotdoom.rgoswami.me)

### CODE REVIEW

**Comment by caisah** [comment]
Hi Rohit,

Unfortunately I rarely do self submissions. If people in the community find it helpful I will.

**Comment by HaoZeke** [comment]
Hi Caisah!
I'm not sure how to prove it is of interest, I have, for example, the number of hits for the site (~40 a day) and the [stargazers](https://github.com/HaoZeke/dotdoom) (currently a modest 5) on the repo.
I noted that being a contributor to MELPA is looked favorably upon, and I am the current maintainer (and contributor) of the [lammps-mode](https://github.com/HaoZeke/lammps-mode) package.
Let me know what would be a good metric.

**Comment by caisah** [comment]
You have some fair points there and indeed I favor elisp packages contributors. 

But from what I see your config is heavily based on a starter pack so I don't think it will be very useful for the regular Emacs user. For example, if someone wants to get into elisp I don't quite see how this config would be of help. (This is only my subjective opinion and it's not meant to criticize your work.)

**Comment by HaoZeke** [comment]
Thanks, that makes sense. It is intentionally based off `doom-emacs`.

**Pull request closed without merging**
